# Assignments for Unit 4 - Projects {#sec-assignment4}

::: {.callout-note appearance="simple"}
This includes the list of assignments for Unit 4 associated with Projects.
:::

## Group Presentation 

Due to present in class on **November 6, 2023**. Teams of approximately 4 students. End product is a 6-10 minute presentation in class using slides and data visualizations. 

::: {.callout-note appearance="warning"}
Absence from in-class presentation will need a Doctor's note or similar documentation to be able to make-up this assignment during Office Hours.
:::

It should include approximately:

- 2 minutes of introduction and background
- 2 minutes defining the scope of your Project
  * Spatial extent (e.g., state of California)
  * Temporal extent (i.e., year-range)
  * Environmental variable(s) to be examined (air pollution, water, radiation, climate, etc.)
- 2 minutes on what the team's hypothesis is and what data will be acquired for exploring that hypothesis.
- 2 minutes on the visualization strategies that will help tell the story. What will the project look like (hand-drawn sketches or design mock-ups are fine).  

### Grading for Group Presentation Project

Total of 150 points.  

* 30 points from other group members (participation grade - anonymous)
* 60 points for quality of presentation slides
  - 10 points for spelling/grammar/formatting
  - 30 points for content, text, and visualizations
  - 20 points for covering 4 topic areas
* 60 points for presentation 
  - 20 points for covering 4 topic areas
  - 10 points for having approximately equal talking time among team members
  - 30 points for content mastery and for answering questions from classmates and Professor Mike

## Individual Visualization

Due by email at 9:45 AM on **November 20, 2023**.  

Assignment is a single visualization of data on the team's chosen topic. Assignment should provide an exported visualization `.png, .pdf, .html` and the `.R script` used to generate the visualization. Source of data should be clearly identified as a comment within the .R script.  

Describe a minimum of three features that were selected to explore the dataset, either in the `.R script` or in the email.  Bullet points are fine.  

## Grading for Individual Visualization Project

Total of 150 points

* 15 points for data source attribution 
* 25 points for description of three features
* 60 points for three features implementation in visualization
* 20 points for aesthetics
* 30 points for labels, legend, and in-visualization annotation 

## Group Visualization

**Due Date**

A group presentation on the progress to date will occur on **December 4th, 2023**.  Final group visualization will be due **December 9th, 2023** at noon (PST).    

Assignment is a visualization on the team's chosen topic. Assignment should provide an exported visualization `.png, .pdf, .html` and the `.R script` used to generate the visualization(s). Source(s) of data should be clearly identified as a comment within the .R script.  

Describe the features that were selected to explore the dataset, either in the `.R script` or in the email. Bullet points are fine.   

Document in a single paragraph how the visualization shows the group theme. I want a brief story of how the visualization illustrates that. 

## Grading for Group Visualization Project

Total of 250 points

* 30 points for data source attribution 
* 30 points for description of features
* 70 points for features implementation in visualization(s)
* 30 points for aesthetics
* 30 points for labels, legend, and in-visualization annotation 
* 30 points for the visualization providing insight into the group theme
* 30 points for group participation - (team grading)